BraintreePOC/Models/Requests/Customer/CreateAddressRequest.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace BraintreePOC.Models.Requests.Customer
{
    public class CreateAddressRequest
    {
        public string PhoneNumber { get; set; }
        public string CountryName { get; set; }
        public string PostalCode { get; set; }
        public string Region { get; set; }
        public string ExtendedAddress { get; set; }
        public string StreetAddress { get; set; }
        public long CustomerId { get; set; }
    }
}

BraintreePOC/Models/Requests/Customer/CreateCustomerCreditCardRequest.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace BraintreePOC.Models.Requests.Customer
{
    public class CreateCustomerCreditCardRequest
    {
        public long CustomerId { get; set; }

        public string ClientNonce { get; set; }

    }
}

BraintreePOC/Models/Requests/Customer/CreateCustomerRequest.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace BraintreePOC.Models.Requests.Customer
{
    public class CreateCustomerRequest
    {
        public string FirstName { get; set; }

        public string LastName { get; set; }

        public string Email { get; set; }

        public string Phone { get; set; }

    }
}

BraintreePOC/Controllers/CheckoutController.cs
using Braintree;
using BraintreePOC.Entities;
using BraintreePOC.Models;
using BraintreePOC.Models.Requests.Checkout;
using BraintreePOC.Models.ViewModels;
using BraintreePOC.Models.ViewModels.Checkout;
using BraintreePOC.Services.Interfaces;
using Microsoft.AspNetCore.Mvc;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace BraintreePOC.Controllers
{
    public class CheckoutController : Controller
    {
        private readonly IBraintreeService braintreeService;
        private readonly BraintreeDbContext dbContext;

        public CheckoutController(IBraintreeService braintreeService, BraintreeDbContext dbContext)
        {
            this.braintreeService = braintreeService;
            this.dbContext = dbContext;
        }

        public async Task<IActionResult> Index([FromForm] IndexRequest request)
        {
            ViewBag.ClientToken = await this.braintreeService.GenerateClientToken(request.Currency);
            return View(request);
        }


        public IActionResult Refund(long transactionId, long customerId)
        {
            ViewBag.TransactionId = transactionId;
            ViewBag.CustomerId = customerId;
            return View();
        }

        public async Task<IActionResult> Payment([FromForm] IndexRequest request)
        {
            ViewBag.ClientToken = await this.braintreeService.GenerateClientToken(request.Currency);

            var paymentViewModel = new PaymentViewModel
            {
                Amount = request.Amount,
                Currency = request.Currency,
                CustomerId = request.CustomerId
            };

            if (request.CustomerId.HasValue)
            {
                paymentViewModel.CustomerCreditCards = dbContext.CreditCards.Where(x => x.CustomerId == request.CustomerId.Value).ToList();
            }

            return View(paymentViewModel);
        }

        [HttpPost]
        public async Task<IActionResult> CreatePurchase([FromBody] CreatePurchaseRequest request)
        {
            var result = await this.braintreeService.CreatePurchase(request);
            return new JsonResult(result);
        }

        [HttpPost]
        public async Task<IActionResult> CreatePurchaseWithToken([FromBody] CreatePurchaseWithTokenRequest request)
        {
            var result = await this.braintreeService.CreatePurchaseWithToken(request);
            return new JsonResult(result);
        }

        public async Task<IActionResult> Result(string id)
        {
            var transactionResponse = await this.braintreeService.GetTransactionById(id);

            var transaction = transactionResponse.Transaction;

            var resultViewModel = new BraintreeTransactionViewModel
            {
                Succeeded = transactionResponse.Succeeded,
                ErrorMessage = transactionResponse.ErrorMessage,
                Amount = transaction.Amount,
                CreatedAt = transaction.CreatedAt,
                Id = transaction.Id,
                Status = transaction.Status,
                Type = transaction.Type,
                UpdatedAt = transaction.UpdatedAt,
                CreditCardDetails = new BraintreeTransactionCreditCardViewModel
                {
                    Bin = transaction.CreditCard?.Bin,
                    CardholderName = transaction.CreditCard?.CardholderName,
                    ExpirationDate = transaction.CreditCard?.ExpirationDate,
                    Last4 = transaction.CreditCard?.LastFour,
                    Token = transaction.CreditCard?.Token,
                    Type = transaction.CreditCard.CardType
                },
                CustomerDetails = new BraintreeTransactionCustomerViewModel
                {
                    Company = transaction.CustomerDetails?.Company,
                    Email = transaction.CustomerDetails?.Email,
                    Fax = transaction.CustomerDetails?.Fax,
                    FirstName = transaction.CustomerDetails?.FirstName,
                    Id = transaction.CustomerDetails?.Id,
                    LastName = transaction.CustomerDetails?.LastName,
                    Phone = transaction.CustomerDetails?.Phone,
                    Website = transaction.CustomerDetails?.Website
                }
            };

            return View(resultViewModel);
        }

        public async Task<IActionResult> Transactions()
        {
            var result = await this.braintreeService.GetAllTransactions();
            return View();
        }



        [HttpPost]
        public async Task<IActionResult> RefundTransaction([FromForm] RefundTransactionRequest request)
        {
            var result = await this.braintreeService.RefundTransaction(request);
            return RedirectToAction("Transactions", "Home", new { customerId = request.CustomerId });
        }
    }
}

BraintreePOC/Controllers/CustomerController.cs
using BraintreePOC.Models;
using BraintreePOC.Models.Requests.Customer;
using BraintreePOC.Services.Interfaces;
using Microsoft.AspNetCore.Mvc;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace BraintreePOC.Controllers
{
    public class CustomerController : Controller
    {
        private readonly IBraintreeService braintreeService;

        public CustomerController(IBraintreeService braintreeService)
        {
            this.braintreeService = braintreeService;
        }

        public async Task<IActionResult> CreateCustomer([FromForm] CreateCustomerRequest request)
        {
            var customerId = await this.braintreeService.CreateCustomer(request);

            if (customerId != null)
            {
                return RedirectToAction("Customers", "Home");
            }
            else
            {
                return RedirectToAction("Error");
            }

        }

        public async Task<IActionResult> CreateAddress([FromForm] CreateAddressRequest request)
        {
            var address = await this.braintreeService.CreateCustomerAddress(request);

            if (address != null)
            {
                return RedirectToAction("Addresses", "Home", new { customerId = request.CustomerId });
            }
            else
            {
                return RedirectToAction("Error");
            }

        }

        [HttpPost]
        public async Task<IActionResult> CreateCustomerCreditCard([FromBody] CreateCustomerCreditCardRequest request)
        {
            var cardToken = await this.braintreeService.CreateCustomerCreditCard(request);
            return new JsonResult(request.CustomerId);
        }
    }
}

BraintreePOC/Controllers/HomeController.cs
using System;
using System.Collections.Generic;
using System.Diagnostics;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.Extensions.Logging;
using BraintreePOC.Models;
using Braintree;
using Microsoft.AspNetCore.Http;
using BraintreePOC.Entities;
using BraintreePOC.Services.Interfaces;

namespace BraintreePOC.Controllers
{
    public class HomeController : Controller
    {
        private readonly ILogger<HomeController> _logger;
        private readonly BraintreeDbContext dbContext;
        private readonly IBraintreeService braintreeService;

        public HomeController(ILogger<HomeController> logger, BraintreeDbContext dbContext, IBraintreeService braintreeService)
        {
            _logger = logger;
            this.dbContext = dbContext;
            this.braintreeService = braintreeService;
        }

        public IActionResult Index()
        {
            var customers = dbContext.Customers.ToList();
            return View(customers);
        }

        public IActionResult Tests()
        {
            return View();
        }

        public IActionResult Customers()
        {
            var customers = dbContext.Customers.ToList();
            return View(customers);
        }

        public IActionResult Addresses(long customerId)
        {
            var addresses = dbContext.Addresses.Where(x => x.CustomerId == customerId).ToList();
            ViewBag.CustomerId = customerId;
            return View(addresses);
        }

        public IActionResult Transactions(long customerId)
        {
            var transactions = dbContext.Transactions.Where(x => x.CustomerId == customerId)
                .OrderByDescending(x => x.Id).ToList();
            return View(transactions);
        }

        public async Task<IActionResult> CreditCards(long customerId)
        {
            var customerCreditCards = dbContext.CreditCards.Where(x => x.CustomerId == customerId).ToList();

            ViewBag.CustomerId = customerId;
            ViewBag.ClientToken = await this.braintreeService.GenerateClientTokenWithoutCurrency();

            return View(customerCreditCards);
        }

        [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
        public IActionResult Error()
        {
            return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
        }
    }
}

BraintreePOC/Views/Home/Addresses.cshtml
@*
    For more information on enabling MVC for empty projects, visit https://go.microsoft.com/fwlink/?LinkID=397860
*@
@{
}
@model List<BraintreePOC.Database.Entities.CustomerAddress>

<div class="p-3">
    <form id="addressForm" asp-action="CreateAddress" asp-controller="Customer">
        <input type="hidden" name="CustomerId" id="customerId" value="@ViewBag.CustomerId" />
        <div class="row">
            <div class="col-md-6">
                <div class="form-group">
                    <label for="firstName">Phone Number</label>
                    <input type="text" name="PhoneNumber" class="form-control" id="phoneNumber" placeholder="Enter phone number">
                </div>
            </div>
            <div class="col-md-6">
                <div class="form-group">
                    <label for="lastName">Country Name</label>
                    <input type="text" name="CountryName" class="form-control" id="countryName" placeholder="Enter country name">
                </div>
            </div>
        </div>
        <div class="row">
            <div class="col-md-6">
                <div class="form-group">
                    <label for="firstName">Postal Code</label>
                    <input type="text" name="PostalCode" class="form-control" id="postalCode" placeholder="Enter postal code">
                </div>
            </div>
            <div class="col-md-6">
                <div class="form-group">
                    <label for="lastName">Region</label>
                    <input type="text" name="Region" class="form-control" id="region" placeholder="Enter region">
                </div>
            </div>
        </div>
        <div class="row">
            <div class="col-md-6">
                <div class="form-group">
                    <label for="firstName">StreetAddress</label>
                    <input type="text" name="StreetAddress" class="form-control" id="streetAddress" placeholder="Enter street address">
                </div>
            </div> 
        </div>

        <hr class="mb-4">
        <div class="text-center">
            <button class="btn btn-primary btn-lg" type="submit">Save Address</button>
        </div>
    </form>
</div>

<div class="p-3">
    <h5>Addresses</h5>
    @if (Model?.Count > 0)
    {
        <table class="table">
            <thead>
                <tr>
                    <th scope="col">Phone Number</th>
                    <th scope="col">Country Name</th>
                    <th scope="col">Postal Code</th>
                    <th scope="col">Region</th>
                    <th scope="col" colspan="2">Street Address</th>
                </tr>
            </thead>
            <tbody>
                @foreach (var address in Model)
                {
                <tr>
                    <td>@address.PhoneNumber</td>
                    <td>@address.CountryName</td>
                    <td>@address.PostalCode</td>
                    <td>@address.Region</td>
                    <td>@address.StreetAddress</td>
                </tr>
                }
            </tbody>
        </table>
    }
    else
    {
        <p>No addresses in the system</p>
    }
</div>

@section scripts {
    <script type="text/javascript" src="~/js/addresses.js" asp-append-version="true"></script>
}

BraintreePOC/Views/Home/CreditCards.cshtml
@model List<BraintreePOC.Database.Entities.CustomerCreditCard>

<div class="p-3">
    <form id="creditCardForm">
        <input type="hidden" id="clientToken" value="@ViewBag.ClientToken" />
        <input type="hidden" id="customerId" value="@ViewBag.CustomerId" />

        <div class="row">
            <div class="col-sm-6 mb-3">
                <label for="cc-name">Cardholder Name</label>
                <div class="form-control" id="cc-name"></div>
                <small class="text-muted">Full name as displayed on card</small>
                <div class="invalid-feedback">
                    Name on card is required
                </div>
            </div>
        </div>
        <div class="row">
            <div class="col-sm-6 mb-3">
                <label for="cc-number">Credit card number</label>
                <div class="form-control" id="cc-number"></div>
                <div class="invalid-feedback">
                    Credit card number is required
                </div>
            </div>
            <div class="col-sm-3 mb-3">
                <label for="cc-expiration">Expiration</label>
                <div class="form-control" id="cc-expiration"></div>
                <div class="invalid-feedback">
                    Expiration date required
                </div>
            </div>
            <div class="col-sm-3 mb-3">
                <label for="cc-expiration">CVV</label>
                <div class="form-control" id="cc-cvv"></div>
                <div class="invalid-feedback">
                    Security code required
                </div>
            </div>
        </div>
        <hr class="mb-4">
        <div class="text-center">
            <button class="btn btn-primary btn-lg" type="submit">Save Credit Card</button>
        </div>
    </form>
</div>

<div class="p-3">
    <h5>Credit Cards</h5>
    @if (Model?.Count > 0)
    {
        <table class="table">
            <thead>
                <tr>
                    <th scope="col">Braintree Token</th>
                    <th scope="col">Last Four</th>
                    <th scope="col">Is Default</th>
                    <th scope="col"></th>
                </tr>
            </thead>
            <tbody>
                @foreach (var creditCard in Model)
                {
                <tr>
                    <td>@creditCard.Token</td>
                    <td>@creditCard.Last4</td>
                    @if (creditCard.IsDefault)
                    {
                        <td style="color:green;">True</td>
                    }
                    else
                    {
                        <td style="color:red;">False</td>
                    }
                    <td>
                        <button disabled="@creditCard.IsDefault" type="button" class="btn btn-success">Make Default</button>
                    </td>
                </tr>
                }
            </tbody>
        </table>
    }
    else
    {
        <p>No cards in the system</p>
    }
</div>

@section scripts {
    <script type="text/javascript" src="~/js/creditcards.js" asp-append-version="true"></script>
}

BraintreePOC/Views/Home/Customers.cshtml
@model List<BraintreePOC.Database.Entities.Customer>

<div class="p-3">
    <form id="customerForm" asp-action="CreateCustomer" asp-controller="Customer">
        <div class="row">
            <div class="col-md-6">
                <div class="form-group">
                    <label for="firstName">First Name</label>
                    <input type="text" name="FirstName" class="form-control" id="firstName" placeholder="Enter first name">
                </div>
            </div>
            <div class="col-md-6">
                <div class="form-group">
                    <label for="lastName">Last Name</label>
                    <input type="text" name="LastName" class="form-control" id="firstName" placeholder="Enter last name">
                </div>
            </div>
        </div>

        <div class="row">
            <div class="col-md-6">
                <div class="form-group">
                    <label for="email">Email Address</label>
                    <input type="email" name="Email" class="form-control" id="email" placeholder="Enter email">
                </div>
            </div>
            <div class="col-md-6">
                <div class="form-group">
                    <label for="phone">Phone</label>
                    <input type="text" name="Phone" class="form-control" id="phone" placeholder="Enter phone">
                </div>
            </div>
        </div>
        <button type="submit" class="btn btn-primary">Save Customer</button>
    </form>
</div>
<div class="p-3">
    <h5>Customers</h5>
    @if (Model?.Count > 0)
    {
        <table class="table">
            <thead>
                <tr>
                    <th scope="col">Braintree ID</th>
                    <th scope="col">First Name</th>
                    <th scope="col">Last Name</th>
                    <th scope="col">Email</th>
                    <th scope="col">Phone</th>
                    <th scope="col"></th>
                    <th scope="col"></th>
                    <th scope="col"></th>
                </tr>
            </thead>
            <tbody>
                @foreach (var customer in Model)
                {
                <tr>
                    <td>@customer.BraintreeId</td>
                    <td>@customer.FirstName</td>
                    <td>@customer.LastName</td>
                    <td>@customer.Email</td>
                    <td>@customer.Phone</td>
                    <td>
                        <a href="@Url.Action("CreditCards","Home",new { customerId = customer.Id })" class="text-decoration-none btn btn-primary">Credit Cards</a>
                    </td>
                    <td>
                        <a href="@Url.Action("Addresses","Home",new { customerId = customer.Id })" class="text-decoration-none btn btn-primary">Addresses</a>
                    </td>
                    <td>
                        <a href="@Url.Action("Transactions","Home",new { customerId = customer.Id })" class="text-decoration-none btn btn-primary">Transactions</a>
                    </td>
                </tr>
                }
            </tbody>
        </table>
    }
    else
    {
        <p>No customers in the system</p>
    }
</div>

BraintreePOC/Views/Home/Index.cshtml
@model List<BraintreePOC.Database.Entities.Customer>

@{
    ViewData["Title"] = "Home Page";
}

<div class="container-fluid">

    <div class="p-3">
        <h4>Legacy Payment</h4>
        <form asp-action="Index" asp-controller="Checkout" method="post">
            <div class="input-group mb-3">
                <div class="input-group-prepend">
                    <span class="input-group-text" id="basic-addon1">Amount : </span>
                </div>
                <input type="number" name="Amount" class="form-control" placeholder="Enter the price">
            </div>
            <div class="form-check">
                <input class="form-check-input" type="radio" name="Currency" id="gbpCurrency" value="GBP" checked>
                <label class="form-check-label" for="gbpCurrency">GBP</label>
            </div>
            <div class="form-check">
                <input class="form-check-input" type="radio" name="Currency" id="usdCurrency" value="USD">
                <label class="form-check-label" for="usdCurrency">USD</label>
            </div>
            <div class="form-check">
                <input class="form-check-input" type="radio" name="Currency" id="eurCurrency" value="EUR">
                <label class="form-check-label" for="eurCurrency">EUR</label>
            </div>
            <div class="pt-3 btn-group" role="group">
                <button type="submit" class="btn btn-primary">Checkout Legacy</button>
            </div>
        </form>
    </div>

    <div class="p-3">
        <h4>3D Payment</h4>
        <form asp-action="Payment" asp-controller="Checkout" method="post">
            @if (Model?.Count > 0)
            {
                <div class="form-group">
                    <label for="customerSelect">Selected Customer</label>
                    <select class="form-control" id="selectedCustomer" name="CustomerId">
                        @foreach (var customer in Model)
                        {
                            var name = customer.FirstName + " " + customer.LastName;
                            <option value="@customer.Id">@name</option>
                        }
                    </select>
                </div>
            }
            <div class="input-group mb-3">
                <div class="input-group-prepend">
                    <span class="input-group-text" id="basic-addon1">Amount : </span>
                </div>
                <input type="number" name="Amount" class="form-control" placeholder="Enter the price">
            </div>
            <div class="form-check">
                <input class="form-check-input" type="radio" name="Currency" id="gbpCurrency" value="GBP" checked>
                <label class="form-check-label" for="gbpCurrency">GBP</label>
            </div>
            <div class="form-check">
                <input class="form-check-input" type="radio" name="Currency" id="usdCurrency" value="USD">
                <label class="form-check-label" for="usdCurrency">USD</label>
            </div>
            <div class="form-check">
                <input class="form-check-input" type="radio" name="Currency" id="eurCurrency" value="EUR">
                <label class="form-check-label" for="eurCurrency">EUR</label>
            </div>
            <div class="pt-3 btn-group" role="group">
                <button type="submit" class="btn btn-primary">Checkout 3D2S</button>
            </div>
        </form>
    </div>
    <div class="p-3">
        <a class="btn btn-success" href="@Url.Action("Customers","Home")">Go to Customers</a>
    </div>
    <div class="p-3">
        <a class="btn btn-success" href="@Url.Action("Tests","Home")">Go to Test Helper</a>
    </div>
</div>



@*<div>
        <a class="btn btn-primary text-decoration-none" href="@Url.Action("Index","Checkout")">Go to Checkout</a>
    </div>*@

BraintreePOC/Views/Home/Tests.cshtml
<h3>Test Helper Page</h3>

<div class="container-fluid">
    <div class="p-3">
        <h4>Valid Card Numbers</h4>
        <table class="table">
            <thead>
                <tr>
                    <th scope="col">Card Number</th>
                    <th scope="col">Card Type</th>
                </tr>
            </thead>
            <tbody>
                <tr>
                    <td>5555555555554444</td>
                    <td>Master Card</td>
                </tr>
                <tr>
                    <td>4111111111111111</td>
                    <td>Visa</td>
                </tr>
                <tr>
                    <td>4005519200000004</td>
                    <td>Visa</td>
                </tr>
                <tr>
                    <td>4012000033330026</td>
                    <td>Visa</td>
                </tr>
            </tbody>
        </table>
    </div>
    <div class="p-3">
        <h4>Invalid Card Numbers</h4>
        <table class="table">
            <thead>
                <tr>
                    <th scope="col">Card Number</th>
                    <th scope="col">Card Type</th>
                </tr>
            </thead>
            <tbody>
                <tr>
                    <td>4000111111111115</td>
                    <td>Visa</td>
                </tr>
                <tr>
                    <td>5105105105105100</td>
                    <td>Master Card</td>
                </tr>
            </tbody>
        </table>
    </div>
    <div class="p-3">
        <h4>Test With Amounts</h4>
        <table class="table">
            <thead>
                <tr>
                    <th scope="col">Amount</th>
                    <th scope="col">Authorization Response</th>
                    <th scope="col">Settlement Response</th>
                </tr>
            </thead>
            <tbody>
                <tr>
                    <td>0.01 - 1999.99</td>
                    <td>Authorized</td>
                    <td>Settled</td>
                </tr>
                <tr>
                    <td>2000.00 - 2999.99</td>
                    <td>Processor Declined with a processor response equal to the amount</td>
                    <td>n/a</td>
                </tr>
                <tr>
                    <td>2000.00 - 2999.99</td>
                    <td>Failed with a 3000 processor response</td>
                    <td>n/a</td>
                </tr>
                <tr>
                    <td>3000.00 - 3000.99</td>
                    <td>Failed with a 3000 processor response (Processor Network Unavailable – Try Again)</td>
                    <td>n/a</td>
                </tr>
                <tr>
                    <td>5001.00</td>
                    <td>Gateway Rejected with a reason of Application Incomplete</td>
                    <td>n/a</td>
                </tr>
            </tbody>
        </table>
    </div>
    <div class="p-3">
        <h4>Test With CVV</h4>
        <table class="table">
            <thead>
                <tr>
                    <th scope="col">CVV</th>
                    <th scope="col">Response</th>
                </tr>
            </thead>
            <tbody>
                <tr>
                    <td>200</td>
                    <td>N (does not match)</td>
                </tr>
                <tr>
                    <td>201</td>
                    <td>U (not verified)</td>
                </tr>
                <tr>
                    <td>301</td>
                    <td>S (issuer does not participate)</td>
                </tr>
                <tr>
                    <td>no value passed</td>
                    <td>I (not provided)</td>
                </tr>
                <tr>
                    <td>any other value</td>
                    <td>M (matches)</td>
                </tr>
            </tbody>
        </table>
    </div>
    <div class="p-3">
        <h4>Test With AVS (Address Verification System)</h4>
        <table class="table">
            <thead>
                <tr>
                    <th scope="col">Billing Postal Code</th>
                    <th scope="col">Response</th>
                </tr>
            </thead>
            <tbody>
                <tr>
                    <td>30000</td>
                    <td>E (AVS system error)</td>
                </tr>
                <tr>
                    <td>30001</td>
                    <td>S (issuing bank does not support AVS)</td>
                </tr>
                <tr>
                    <td>20000</td>
                    <td>N (does not match)</td>
                </tr>
                <tr>
                    <td>2001</td>
                    <td>U (not verified)</td>
                </tr>
                <tr>
                    <td>no value passed</td>
                    <td>I (not provided)</td>
                </tr>
                <tr>
                    <td>any other value</td>
                    <td>M (matches)</td>
                </tr>
            </tbody>
        </table>
    </div>
</div>

BraintreePOC/Views/Home/Transactions.cshtml
@model List<BraintreePOC.Database.Entities.CustomerTransaction>

<div class="p-3">
    <h5>Transactions</h5>
    @if (Model?.Count > 0)
    {
        <table class="table">
            <thead>
                <tr>
                    <th scope="col">Braintree Id</th>
                    <th scope="col">Amount</th>
                    <th scope="col">Status</th>
                    <th scope="col">Processor Response Code</th>
                    <th scope="col">Processor Response Text</th>
                    <th scope="col">Was Successfull</th>
                    <th scope="col"></th>
                </tr>
            </thead>
            <tbody>
                @foreach (var transaction in Model)
                {
                    <tr>
                        <td>@transaction.BraintreeTransactionId</td>
                        <td>@transaction.Amount</td>
                        <td>@transaction.Status</td>
                        <td>@transaction.ProcessorResponseCode</td>
                        <td>@transaction.ProcessorResponseText</td>
                        @if (transaction.WasSuccessfull)
                        {
                            <td style="color:green;">True</td>
                        }
                        else
                        {
                            <td style="color:red;">False</td>
                        }
                        <td>
                            <a href="@Url.Action("Refund","Checkout",new { transactionId = transaction.Id , customerId = transaction.CustomerId})" class="text-decoration-none btn btn-primary">Refund</a>
                        </td>
                    </tr>
                }
            </tbody>
        </table>
    }
    else
    {
        <p>No transaction in the system</p>
    }
</div>

@section scripts {
    <script type="text/javascript" src="~/js/addresses.js" asp-append-version="true"></script>
}